Use cmake instead of autotools in Amegic

diff --git a/AMEGIC++/Main/makelibs.in b/AMEGIC++/Main/makelibs.in
--- a/AMEGIC++/Main/makelibs.in
+++ b/AMEGIC++/Main/makelibs.in
@@ -25,8 +25,7 @@ defaults(){
 
 defaults;
 
-which scons > /dev/null 2>&1 && SCONS=TRUE
-while getopts hsmcnoj:i: OPT
+while getopts hmcnoj:i: OPT
 do
   case $OPT in
   c) CLEAN=TRUE ;;
@@ -34,7 +33,6 @@ do
   o) ONE=TRUE ;;
   j) JOBS=$OPTARG ;;
   m) LIBMODE=1 ;;
-  s) SCONS=FALSE ;;
   i) IPATH=$OPTARG ;;
   h) print_help && exit 0 ;;
   \?)
@@ -64,31 +62,27 @@ if [ "$ONE" = "TRUE" ] ; then
   done
 fi
 
-if [ "$SCONS" = "TRUE" ] ; then
-  test -z "$IPATH" || IPATH="incdir="$IPATH
-  @BINDIR@/make2scons x;
-  for J in $DIRS ; do
-    @BINDIR@/make2scons $J $LIBMODE;
-  done
-  scons -j$JOBS install $IPATH;
-  exit 0;
-fi
-
 if test -z "$CXX"; then export CXX="@CXX@"; fi
 if test -z "$CXXFLAGS"; then export CXXFLAGS="@CXXFLAGS@"; fi
-if test -z "$LDFLAGS"; then export LDFLAGS="@LDFLAGS@"; fi
-if test -z "$LIBS"; then export LIBS="@LIBS@"; fi
-if test -z "$CPPFLAGS"; then export CPPFLAGS="@CPPFLAGS@"; fi
 if test -z "$CC"; then export CC="@CC@"; fi
 if test -z "$CFLAGS"; then export CFLAGS="@CFLAGS@"; fi
 if test -z "$FC"; then export FC="@FC@"; fi
 if test -z "$FCFLAGS"; then export FCFLAGS="@FCFLAGS@"; fi
-if test -z "$CXXCPP"; then export CXXCPP="@CXXCPP@"; fi
-
-if echo "@host@" | grep -q "i686"; then
-    export CXX="$CXX -m32"
-    export CC="$CC -m32"
-    export LDFLAGS="$LDFLAGS -m32"
+if test -z "$CMAKE"; then export CMAKE="@CMAKE_COMMAND@"; fi
+if test -z "$SHERPA_CMAKE_PATH"; then export SHERPA_CMAKE_PATH="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_DATADIR@/SHERPA-MC"; fi
+if [[ ! -f $CMAKE ]]; then
+  echo "makelibs: the original cmake is not present in the system. Falling back to 'cmake3' or 'cmake'"
+  if [[ `type -p cmake3` != "" ]]; then
+    export CMAKE=cmake3
+  else
+    if [[ `type -p cmake` != "" ]]; then
+      export CMAKE=cmake
+    else
+      echo "makelibs: cannot find cmake in the system" 
+      exit 1
+    fi
+  fi
+  echo "makelibs: using $CMAKE"
 fi
 
 test -z "$IPATH" || IPATH="CURRENT_SHERPASYS="$IPATH
@@ -97,35 +91,35 @@ for J in $DIRS ; do
   echo "$J";
   echo "======================"
   cd $J 
-  test -f Makefile.am.orig || cp Makefile.am Makefile.am.orig
-  test -f configure.in.orig || cp configure.in configure.in.orig
+  test -f CMakeLists.txt.orig || cp CMakeLists.txt CMakeLists.txt.orig
   if test $LIBMODE -eq 1; then
-    cp configure.in.orig configure.in
-    diff -q Makefile.am Makefile.am.orig || cp Makefile.am.orig Makefile.am
+    cp CMakeLists.txt.orig CMakeLists.txt
+    diff -q CMakeLists.txt CMakeLists.txt.orig || cp CMakeLists.txt.orig CMakeLists.txt
   elif test $LIBMODE -eq 2; then
-    sed -r '/[1-2]_[0-9*]__/ d' < configure.in.orig > configure.in
+    sed -r '/[1-2]_[0-9*]__/ d' < CMakeLists.txt.orig > CMakeLists.txt
     libname="Proc_"$(basename $(pwd))
     sources=$(for i in $(find . -name \*.C | grep -v fsrchannels); do printf $i | sed 's/$/ /1' | tr '\n' ' '; done)
-    echo "AUTOMAKE_OPTIONS = subdir-objects
-AM_CXXFLAGS = @AM_CXXFLAGS@
-AM_LDFLAGS = @AM_LDFLAGS@
-lib_LTLIBRARIES = lib${libname}.la
-lib${libname}_la_SOURCES = ${sources}
-CURRENT_SHERPASYS ?= @INCLUDEDIR@
-INCLUDES = -I\$(CURRENT_SHERPASYS)" > Makefile.am.new
+    echo "
+project(${libname} LANGUAGES C CXX)
+cmake_minimum_required(VERSION 3.11.0)
+find_package(SHERPA-MC PATHS ${SHERPA_CMAKE_PATH} REQUIRED)
+include(\"GNUInstallDirs\")
+set(lib${libname}_la_SOURCES  ${sources})
+add_library( ${libname} SHARED \${lib${libname}_la_SOURCES})
+amegic_handle_shared_library(${libname})
+set(CMAKE_INSTALL_PREFIX \${PROJECT_SOURCE_DIR}/../)
+install(TARGETS ${libname} DESTINATION \${CMAKE_INSTALL_PREFIX}/\${CMAKE_INSTALL_LIBDIR})
+" > CMakeLists.txt.new
     fsrdir=$(find . -name fsrchannels*)
-    test -d $fsrdir && echo "SUBDIRS = ${fsrdir}" >> Makefile.am.new
-    diff -q Makefile.am Makefile.am.new || mv Makefile.am.new Makefile.am
+    test -f $fsrdir/CMakeLists.txt && echo "add_subdirectory(${fsrdir})" >> CMakeLists.txt.new
+    diff -q CMakeLists.txt CMakeLists.txt.new || mv CMakeLists.txt.new CMakeLists.txt
   fi
-  if test -f configure.in; then
-  autoreconf -fi
-  ./configure --libdir='${prefix}/lib'
+  if test -f CMakeLists.txt; then
+  $CMAKE -S . -B . -DCMAKE_INSTALL_LIBDIR=lib || ( echo "cmake in $I failed" ; exit 1)
   if `test "$CLEAN" = "TRUE"` ; then make clean ; fi
-  if ! make install -j $JOBS $IPATH; then
-    echo "makeinstall: error: \"make install\" in $I failed"
-    exit 1
-  fi
-  if `! test "$POSTCLEAN" = "FALSE"` ; then make distclean ; fi
+  $CMAKE --build . -j $JOBS $IPATH || ( echo "cmake --build in $I failed" ; exit 1)
+  $CMAKE --install . || ( echo "cmake --install in $I failed" ; exit 1)
+  #if `! test "$POSTCLEAN" = "FALSE"` ; then rm -rf CMakeFiles CMakeCache ; fi
   fi
   cd -
 done
