changes in makelibs script: added possibility to compile single subdirectory, option '-o'

diff --git a/SHERPA-1.0/Run/makelibs b/SHERPA-1.0/Run/makelibs
--- a/SHERPA-1.0/Run/makelibs
+++ b/SHERPA-1.0/Run/makelibs
@@ -6,15 +6,45 @@
 
 DIRS=`find Process -name P?_?`" "`find Process -name P?_??`
 
-for I in $* ; do
-  if [ "$I" = "-c" ]; then CLEAN=TRUE ;
-  elif [ "$I" = "-h" ]; then \
-    echo "makelibs options: -c \"make clean\" before compiling" && \
-    echo "                  -h display this help and exit" && \
-    exit 0
-  else echo "makelibs: error: unrecognized option $I" && exit 1 ;
-  fi
+print_help(){
+  echo "makelibs version 1.0" && echo && \
+  echo "options: -c \"make clean\" before compiling" && \
+  echo "         -o install single module" && \
+  echo "         -h display this help and exit" && echo
+}
+
+while getopts :hco OPT
+do
+  case $OPT in
+  c) CLEAN=TRUE ;; 
+  o) ONE=TRUE ;;
+  h) print_help && exit 0 ;;
+  \?)
+    shift `expr $OPTIND - 1`
+    if [ "$1" = "--help" ]; then print_help && exit 0;
+    else 
+      echo -n "makelibs: error: unrecognized option "
+      if [ $OPTARG != "-" ]; then echo "'-$OPTARG'. try '-h'"
+      else echo "'$1'. try '-h'"
+      fi
+      print_help && exit 1
+    fi
+    shift 1
+    OPTIND=1
+  esac
 done
+
+if [ "$ONE" = "TRUE" ] ; then 
+  echo "makelibs: select module ( q) to quit )"
+  select DIRS in $DIRS ; do
+    if [ "$DIRS" != "" ] ; then 
+      SINGLE="TRUE"
+      break
+    else 
+      if [ "$REPLY" = "q" ] || [ "$REPLY" = "Q" ]  ; then exit ; fi
+    fi
+  done
+fi
 
 for J in $DIRS ; do
   echo "."
