Merging branches/macos back into trunk: Support for MacOS   - Build system improvements for the handling of Fortran compiler/library   - Fixes for problems in Cluster_Partons which became apparent on MacOS

diff --git a/SHERPA/Run/makelibs b/SHERPA/Run/makelibs
--- a/SHERPA/Run/makelibs
+++ b/SHERPA/Run/makelibs
@@ -52,7 +52,14 @@ for J in $DIRS ; do
   echo "$J";
   echo "======================"
   cd $J 
-  libtoolize --force
+  if test -x "$(which libtoolize)"; then
+      libtoolize --force;
+  elif test -x "$(which glibtoolize)"; then
+      glibtoolize --force;
+  else
+    echo "Error: libtoolize not found."
+    exit 1
+  fi
   aclocal
   automake -a
   autoconf
