new config strategy

diff --git a/TOOLS/makedist b/TOOLS/makedist
--- a/TOOLS/makedist
+++ b/TOOLS/makedist
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-DIRS="ATOOLS-2.0 BEAM-1.0 PDF-1.0 MODEL-1.0 PHASIC++-1.0"
-DIRS=$DIRS" EXTRA_XS-1.0 ADICIC++-0.0 APACIC++-2.0 AMEGIC++-2.0 AMISIC++-1.0"
-DIRS=$DIRS" AHADIC++-0.0 HADRONS++-0.0 ANALYSIS-1.0 SHERPA-1.0 COMPARE-1.0"
 DISTDIR=`date +'%y-%m-%d'`
 
 ECOPT=""
@@ -10,7 +7,6 @@ for I in $* ; do
   if [ "$I" = "-f" ]; then DISTDIR=$DISTDIR"_"`date +'%H-%M'` 
   elif [ "$I" = "-n" ]; then DNAME=TRUE
   elif [ "$I" = "-u" ]; then COMP=FALSE
-  elif [ "$I" = "-o" ]; then ONE=TRUE
   elif [ "$I" = "--clean" ]; then ALLCLEAN=TRUE 
   elif [ "$I" = "--configure" ]; then CONFIGURE=TRUE 
   elif [ "$I" = "--hide-cvs" ]; then ECOPT=$ECOPT" --disable-cvsinclude" && CONFIGURE=TRUE
@@ -23,7 +19,6 @@ for I in $* ; do
     echo "options: -f             include full time information in distribution name" && \
     echo "         -n <name>      write compressed distribution to <name>.tar.gz" && \
     echo "         -u             distribute uncompressed modules" && \
-    echo "         -o             create distribution of single module" && \
     echo "         --clean        execute 'make clean' before 'make dist'" && \
     echo "         --configure    configure before 'make dist' (enabled with '--total')" && \
     echo "         --total        rebuild 'Makefile.in's' and 'configure's' before 'make dist'" && \
@@ -38,17 +33,6 @@ for I in $* ; do
   fi
 done
 
-if [ "$ONE" = "TRUE" ] ; then 
-  echo "makeinstall: select module ( q) to quit )"
-  select DIRS in $DIRS ; do
-    if [ "$DIRS" != "" ] ; then 
-      break
-    else 
-      if [ "$REPLY" = "q" ] || [ "$REPLY" = "Q" ]  ; then exit ; fi
-    fi
-  done
-fi
-
 if test -d $DISTDIR ; then
   echo "makedist: error: temporary directory '$DISTDIR' exists"
   exit 1
@@ -62,70 +46,40 @@ fi
 echo "*************************************"
 echo "*  creating distribution of SHERPA  *"
 echo "*************************************"
-mkdir $DISTDIR/
-ALL=
-for I in $DIRS;
-do
-  if test -d $I; then
-    echo "====================================="
-    echo " making dist in $I"
-    echo "====================================="
-    ALL=$ALL" "$I.tar.gz
-    cd $I 
-    if [ "$TOTAL" = "TRUE" ]; then
-      libtoolize --force
-      aclocal
-      automake -a
-      autoconf
-    fi
-    if [ "$CONFIGURE" = "TRUE" ]; then 
-      ./configure $ECOPT
-    fi
-    if [ "$ALLCLEAN" = "TRUE" ]; then 
-      make clean 
-    fi
-    CONTINUE="r"
-    while [ "$CONTINUE" = "r" ]; do 
-      CONTINUE=""
-      if ! make dist ; then 
-	echo "makedist: error: \"make dist\" in $I failed"
-        if [ ! "$NOABORT" = "TRUE" ]; then
-          until [ "$CONTINUE" = "y" ] || [ "$CONTINUE" = "n" ] || [ "$CONTINUE" = "r" ]; do
-    	    if ! read -t 300 -n 1 -p "continue anyway (y/n/r/b) ? " CONTINUE ; then
-	      CONTINUE="n"
-	    fi
-	    echo ""
-	    if [ "$CONTINUE" = "n" ]; then
-              exit 1
-	    elif [ "$CONTINUE" = "b" ]; then 
-              bash 
-	      CONTINUE="r"
-	    fi
-	  done
-        fi
-      fi
-    done
-    mv $I.tar.gz ../$DISTDIR/$I.tar.gz
-    cd ..
-  fi
-done;
-cp -r TOOLS/ $DISTDIR/
-cd $DISTDIR
-  rm TOOLS/*~ TOOLS/\#* TOOLS/.\#*
-  if [ "$COMP" = "FALSE" ] ; then
-    for I in $ALL; do
-      tar -xzf $I
-    done
-    rm -rf $ALL
-  else
-    tar -czvf $DISTDIR.tar.gz $ALL TOOLS
-    mv $DISTDIR.tar.gz ..
-  fi
-cd ..
-if [ "$COMP" = "FALSE" ] ; then
-  tar -czvf $DISTDIR.tar.gz $DISTDIR
+if [ "$TOTAL" = "TRUE" ]; then
+  libtoolize --force
+  aclocal
+  automake -a
+  autoconf
 fi
-rm -rf $DISTDIR
+if [ "$CONFIGURE" = "TRUE" ]; then 
+  ./configure $ECOPT
+fi
+if [ "$ALLCLEAN" = "TRUE" ]; then 
+  make clean 
+fi
+CONTINUE="r"
+while [ "$CONTINUE" = "r" ]; do 
+  CONTINUE=""
+  if ! make dist ; then 
+    echo "makedist: error: \"make dist\" in $I failed"
+    if [ ! "$NOABORT" = "TRUE" ]; then
+      until [ "$CONTINUE" = "y" ] || [ "$CONTINUE" = "n" ] || [ "$CONTINUE" = "r" ]; do
+        if ! read -t 300 -n 1 -p "continue anyway (y/n/r/b) ? " CONTINUE ; then
+	  CONTINUE="n"
+        fi
+        echo ""
+        if [ "$CONTINUE" = "n" ]; then
+          exit 1
+        elif [ "$CONTINUE" = "b" ]; then
+          bash 
+          CONTINUE="r"
+        fi
+      done
+    fi
+  fi
+done
+mv SHERPA-MC-1.0.tar.gz $DISTDIR.tar.gz
 echo -e "\nwrote distribution to '$DISTDIR".tar.gz"'\n"
 exit 0
 
