"ready-for-release" scripts

diff --git a/TOOLS/makeinstall b/TOOLS/makeinstall
--- a/TOOLS/makeinstall
+++ b/TOOLS/makeinstall
@@ -1,9 +1,12 @@
 #!/bin/bash
+RELEASE=#"TRUE"
+LOGFILE="sherpa_install.log"
 
-DIRS="ATOOLS-2.0 PDF-1.0 BEAM-1.0 PHASIC++-1.0 MODEL-1.0"
+DIRS="ATOOLS-2.0 BEAM-1.0 PDF-1.0 MODEL-1.0 PHASIC++-1.0"
 DIRS=$DIRS" EXTRA_XS-1.0 APACIC++-2.0 AMEGIC++-2.0"
-#DIRS=$DIRS" AMISIC++-1.0 COMPARE-1.0"
+#DIRS=$DIRS" AMISIC++-1.0 ADICIC++-1.0"
 DIRS=$DIRS" SHERPA-1.0"
+#DIRS=$DIRS" COMPARE-1.0"
 
 ECXXFLAGS=""
 EFFLAGS=""
@@ -13,6 +16,9 @@ for I in $* ; do
   if [ "$I" = "-c" ]; then CONFIGURE=TRUE 
   elif [ "$I" = "-t" ]; then TOTAL=TRUE && CONFIGURE=TRUE
   elif [ "$I" = "-e" ]; then EXTRACT=TRUE
+  elif [ "$I" = "-f" ]; then RELEASE=FALSE
+  elif [ "$I" = "-r" ]; then RELEASE=TRUE
+  elif [ "$I" = "-s" ]; then SCRIPT=TRUE
   elif [ "$I" = "--clean" ]; then CLEAN=TRUE
   elif [ "$I" = "--clean-run" ]; then RUNCLEAN=TRUE
   elif [ "$I" = "--no-abort" ]; then NOABORT=TRUE
@@ -26,6 +32,9 @@ for I in $* ; do
     echo "options: -c             configure before compiling (enabled with '-t')" && \
     echo "         -t             rebuild 'Makefile.in's and 'configure' before compiling" && \
     echo "         -e             extract tar files" && \
+    echo "         -f             display the full information on the setup" && \
+    echo "         -r             display minimal information but write a logfile instead" && \
+    echo "         -s             create simple install scripts to be customized by the user" && \
     echo "         --clean        execute 'make clean' in every module before compiling" && \
     echo "         --clean-run    execute './SHERPA-1.0/Run/makeclean' before compiling" && \
     echo "         --no-abort     ignore exit status of 'make'" && \
@@ -48,21 +57,52 @@ if [ ! "$ECXXFLAGS" = "" ]; then ECXXFLAGS="CXXFLAGS="$ECXXFLAGS ; fi
 if [ ! "$EFFLAGS" = "" ]; then EFFLAGS="FFLAGS="$EFFLAGS ; fi
 if [ "$EMOPT" = "" ]; then EMOPT="-j2" ; fi
 
-if test "$EXTRACT" = "TRUE" ; then
-  echo "**************************************"
-  echo "*   extracting the SHERPA package    *"
-  echo "**************************************"
+if [ "$SCRIPT" = "TRUE" ] ; then 
+  echo "makeinstall: creating simple install scripts"
+  read -t 60 -p "please input the desired name: " NAME
+  if ! test -f $NAME ; then 
+    echo -e "#!/bin/bash\n\nlibtoolize --force\naclocal\nautomake -a\nautoconf\n" > $NAME
+    echo -e "./configure\nmake install" >> $NAME
+  else
+    echo "makeinstall: error: file '$NAME' already exists"
+  fi
+  NAME=$NAME"_all"
+  if ! test -f $NAME ; then 
+    echo -e "#!/bin/bash\n\nDIRS=\"$DIRS\"\n\nfor I in \$DIRS ; do\n\n  cd \$I\n" > $NAME
+    echo -e "  libtoolize --force\n  aclocal\n  automake -a\n  autoconf\n" >> $NAME
+    echo -e "  ./configure\n  make install\n\n  cd ../\n\ndone" >> $NAME
+  else
+    echo "makeinstall: error: file '$NAME' already exists"
+  fi
+  exit 0
+fi
+
+if [ "$EXTRACT" = "TRUE" ] ; then
+  if [ "$RELEASE" = "TRUE" ] ; then
+    echo -e "\n\e[1m\e[31m******************************************************\e[0m"
+    echo -e "\e[1m\e[31m*\e[0m\e[1m           Extracting the SHERPA package            \e[31m*\e[0m"
+    echo -e "\e[1m\e[31m******************************************************\e[0m\n"
+  else
+    echo "**************************************"
+    echo "*   Extracting the SHERPA package    *"
+    echo "**************************************"
+  fi
   ALL=
   for I in $DIRS;
   do
     if test -s $I.tar.gz; then
-      echo "makeinstall: testing for $I"
       if `test ! -d $I` || `test "$FORCE" = "TRUE"` ; then 
-        echo "======================================"
-        echo " extracting $I"
-        echo "======================================"
-        tar -xzvf $I.tar.gz
-        ALL=$ALL" "$I.tar.gz
+        if [ ! "$RELEASE" = "TRUE" ] ; then
+          echo "======================================"
+          echo " extracting $I"
+          echo "======================================"
+          tar -xzvf $I.tar.gz
+	else
+	  echo -ne "extracting module $I ...\r"
+          tar -xzf $I.tar.gz > /dev/null
+          echo -e "\e[32m\t\t\t\t\t\t  done\e[0m"
+        fi
+        ALL=$ALL" "$I.tar.gz 
       else
         echo "makeinstall: warning: directory $I already present"
       fi
@@ -73,54 +113,105 @@ if test "$EXTRACT" = "TRUE" ; then
   rm -f $ALL
 fi
 
-echo "**************************************"
-echo "*   installing the SHERPA package    *"
-echo "**************************************"
+if [ "$RELEASE" = "TRUE" ] ; then
+  echo -e "\n\e[32m******************************************************\e[0m"
+  echo -e "\e[32m*\e[0m\e[5m\e[1m           Installing the SHERPA package            \e[0m\e[32m*\e[0m"
+  echo -e "\e[32m******************************************************\e[0m\n"
+  echo -e "writing stdout and stderr to '$LOGFILE'\n"
+  echo -e "Starting installation at '$HOSTNAME' (architecture $HOSTTYPE) on `date`\n" > $LOGFILE
+  echo -e "PATH=$PATH\n\nLD_LIBRARY_PATH=$LD_LIBRARY_PATH\n\nCLHEPDIR=$CLHEPDIR\n" >> $LOGFILE
+  echo -en "gcc --version -> " >> $LOGFILE && gcc --version >> $LOGFILE
+else
+  echo "**************************************"
+  echo "*   Installing the SHERPA package    *"
+  echo "**************************************"
+fi
 if test "$RUNCLEAN" = "TRUE" ; then
   if cd SHERPA-1.0/Run ; then
     ./makeclean
     cd ../..
   fi
 fi
+
 for I in $DIRS;
 do
   if test -d $I; then
-    echo "======================================"
-    echo " making install in $I"
-    echo "======================================"
+    if [ ! "$RELEASE" = "TRUE" ] ; then
+      echo "======================================"
+      echo " making install in $I"
+      echo "======================================"
+    else
+      echo -ne "installing module $I ...\r"
+    fi
     cd $I 
     if `test "$TOTAL" = "TRUE"` ; then
-      libtoolize --force
-      aclocal
-      automake -a
-      autoconf
+      if [ "$RELEASE" = "TRUE" ] ; then
+        libtoolize --force >> ../$LOGFILE 2>&1
+        aclocal >> ../$LOGFILE 2>&1
+        automake -a >> ../$LOGFILE 2>&1
+        autoconf >> ../$LOGFILE 2>&1
+      else
+        libtoolize --force
+        aclocal
+        automake -a
+        autoconf
+      fi
     fi
     if test "$CONFIGURE" = "TRUE" ; then
-      ./configure "$ECOPT"
+      if [ "$RELEASE" = "TRUE" ] ; then
+        ./configure "$ECOPT" >> ../$LOGFILE 2>&1
+      else
+        ./configure "$ECOPT"
+      fi
     fi
     if `test "$CLEAN" = "TRUE"` ; then 
-      make clean
+      if [ "$RELEASE" = "TRUE" ] ; then
+        make clean >> ../$LOGFILE 2>&1
+      else
+        make clean
+      fi
     fi
     CONTINUE="r"
     while test "$CONTINUE" = "r" ; do 
       CONTINUE=""
-      if ! ( if [ "$ECXXFLAGS" = "" ] && [ "$EFFLAGS" = "" ] ; then make install $EMOPT 
-             elif [ "$EFFLAGS" = "" ] ; then make install $EMOPT "$ECXXFLAGS" 
-             elif [ "$ECXXFLAGS" = "" ] ; then make install $EMOPT "$EFFLAGS" 
-             else make install $EMOPT "$ECXXFLAGS" "$EFFLAGS" 
-             fi ) ; then
-	echo "makeinstall: error: \"make install\" in $I failed"
-        if test ! "$NOABORT" = "TRUE" ; then
+      if ! ( if [ "$RELEASE" = "TRUE" ] ; then
+	       if [ "$ECXXFLAGS" = "" ] && [ "$EFFLAGS" = "" ] ; then make install $EMOPT >> ../$LOGFILE 2>&1 
+               elif [ "$EFFLAGS" = "" ] ; then make install $EMOPT "$ECXXFLAGS" >> ../$LOGFILE 2>&1 
+               elif [ "$ECXXFLAGS" = "" ] ; then make install $EMOPT "$EFFLAGS" >> ../$LOGFILE 2>&1 
+               else make install $EMOPT "$ECXXFLAGS" "$EFFLAGS" >> ../$LOGFILE 2>&1 
+               fi
+             else 
+               if [ "$ECXXFLAGS" = "" ] && [ "$EFFLAGS" = "" ] ; then make install $EMOPT 
+               elif [ "$EFFLAGS" = "" ] ; then make install $EMOPT "$ECXXFLAGS" 
+               elif [ "$ECXXFLAGS" = "" ] ; then make install $EMOPT "$EFFLAGS" 
+               else make install $EMOPT "$ECXXFLAGS" "$EFFLAGS" 
+               fi 
+	     fi ) ; then
+        if [ "$RELEASE" = "TRUE" ] ; then 
+          echo -e "\e[31m\t\t\t\t\t\tfailed\e[0m" 
+        else 
+	  echo "makeinstall: error: \"make install\" in $I failed"
+        fi
+        if [ ! "$NOABORT" = "TRUE" ] ; then
           until test "$CONTINUE" = "y" || test "$CONTINUE" = "n" || test "$CONTINUE" = "r" ; do
     	    if ! read -t 300 -p "continue anyway (y/n/r) ? " CONTINUE ; then
 	      echo ""
 	      CONTINUE="n"
 	    fi
-	    if test "$CONTINUE" = "n" ; then
+	    if [ "$CONTINUE" = "n" ] ; then
+	      if [ "$RELEASE" = "TRUE" ] ; then
+                `echo clear`
+	        echo -e "\nIt seems that you have problems setting up the package $I"
+	        echo -e "If they persist please contact us under\n"
+	        echo -e "  krauss@theory.phy.tu-dresden.de\n"
+		echo -e "Please send us the complete installation logfile '$LOGFILE'\n"
+	      fi
               exit 1
 	    fi
 	  done
         fi
+      else
+        if [ "$RELEASE" = "TRUE" ] ; then echo -e "\e[32m\t\t\t\t\t\t  done\e[0m" ; fi
       fi
     done
     cd ..
@@ -129,3 +220,19 @@ do
     exit 2
   fi
 done;
+sleep 1
+if [ "$RELEASE" = "TRUE" ] ; then
+  if test ! "$CONTINUE" = "n" ; then
+    `echo clear`
+    echo -e "\e[34m*******************************************************"
+    echo -e "*\e[0m                                                     \e[34m*"
+    echo -e "*\e[0m\e[1m   Initial setup of Sherpa successfully completed    \e[0m\e[34m*"
+    echo -e "*\e[0m                                                     \e[34m*"
+    echo -e "*\e[0m  Please check our web page for recent developments  \e[34m*"
+    echo -e "*\e[0m                                                     \e[34m*"
+    echo -e "*\e[0m    http://www.physik.tu-dresden.de/~krauss/hep/     \e[34m*"
+    echo -e "*\e[0m                                                     \e[34m*"
+    echo -e "*******************************************************\e[0m"
+    echo -e "\nhave a nice day `whoami`\n"
+  fi
+fi
